{
 "title": "S3GW",
 "description": "https://s3gw.io/",
 "tags": [ "S3GW" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "operation", "label": "Focused S3 Operation", "query": { "query": "label_values(op)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(rgw_req_total{job=\"s3gw-status\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "What's happening?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Queue [Gauge]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rgw_qactive{instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "rgw_qlen{instance=\"$instance\"}",
     "legendFormat": "Total Queue Length"
    }
   ]
  },
  {
   "title": "Requests [Rate]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(rgw_req_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Requests"
    },
    {
     "expr": "rate(rgw_failed_req_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Failed Requests"
    }
   ]
  },
  {
   "title": "All Ops Average Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rgw_op_svc_time_bucket{op=~\"$operation\",instance=\"${instance}\"})",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.9, rgw_op_svc_time_bucket{op=~\"$operation\",instance=\"${instance}\"})",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, rgw_op_svc_time_bucket{op=~\"$operation\",instance=\"${instance}\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rgw_op_svc_time_bucket{op=~\"$operation\",instance=\"${instance}\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Common Ops [Rate]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(rgw_op_svc_time_count{op=~\"get_obj|put_obj|create_bucket|delete_obj|list_bucket|list_buckets|delete_bucket\", instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "RGW Throughput [byte/s]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(rgw_put_b_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(rgw_get_b_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "GET"
    }
   ]
  },
  {
   "title": "All Ops [Rate]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(rgw_op_svc_time_count{instance=\"${instance}\"}[$__rate_interval]) > 0",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Focus: S3 Operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$operation Service Time",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(rgw_op_svc_time_bucket{op=\"$operation\",instance=\"${instance}\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$operation histogram",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rgw_op_svc_time_bucket{op=\"$operation\", instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "S3GW: Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Transaction Retried [Rate]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(rgw_sfs_retry_total_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "transactions ran with retry"
    },
    {
     "expr": "rate(rgw_sfs_retry_retried_count_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "retried transactions"
    },
    {
     "expr": "rate(rgw_sfs_retry_failed_count_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "retried until failure"
    }
   ]
  },
  {
   "title": "SQLite Connections [Gauge]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sfs_sqlite_connection_count{instance=\"$instance\"}",
     "legendFormat": "SQLite Connections"
    }
   ]
  },
  {
   "title": "SFS SQLite DB/WAL Size [Gauge]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sfs_sqlite_db_bytes{instance=\"$instance\"}",
     "legendFormat": "DB"
    },
    {
     "expr": "sfs_sqlite_db_wal_bytes{instance=\"$instance\"}",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "SFS Filesystem [Gauge]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sfs_filesystem_total_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sfs_filesystem_avail_bytes{instance=\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "S3GW: Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "GC Runs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rgw_sfs_gc_process_exit{instance=\"$instance\"}",
     "legendFormat": "GC Process Exit"
    },
    {
     "expr": "rgw_sfs_gc_count_total{instance=\"$instance\"}",
     "legendFormat": "Total GC Runs"
    }
   ]
  },
  {
   "title": "Last GC Total Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rgw_sfs_gc_process_time{instance=\"$instance\"}",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Last GC Run Elapsed Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rgw_sfs_gc_pending_objects_data_elapsed{instance=\"$instance\"}",
     "legendFormat": "Pending Objects Data"
    },
    {
     "expr": "rgw_sfs_gc_deleted_buckets_elapsed{instance=\"$instance\"}",
     "legendFormat": "Deleted Buckets"
    },
    {
     "expr": "rgw_sfs_gc_deleted_objects_elapsed{instance=\"$instance\"}",
     "legendFormat": "Deleted Objects"
    },
    {
     "expr": "rgw_sfs_gc_pending_multiparts_data_elapsed{instance=\"$instance\"}",
     "legendFormat": "Pending Multiparts Data"
    }
   ]
  },
  {
   "title": "S3GW: SQLite Query Profiling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQLite Profiling: Query Time",
     "type": "heatmap",
     "description": "See --rgw-sfs-sqlite-profile 1",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(rate(rgw_prom_hist_sfs_sqlite_profile_bucket{instance=\"${instance}\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}